name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: CentOS Deploys

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build application
      run: CI=false npm run build

    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER: 45.33.14.185
        USER: root
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key
        
        rsync -avz --delete -e "ssh -i private_key" ./build/ root@45.33.14.185:/var/www/portfolio_prod/personal-portfolio-updated/build/
        rsync -avz --delete -e "ssh -i private_key" ./ root@45.33.14.185:/var/www/portfolio_prod/personal-portfolio-updated/

        ssh -i private_key root@45.33.14.185 'systemctl reload nginx'
        rm private_key
