name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build application
      run: CI=false npm run build

    - name: Deploy to server
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/my_key.pub
        chmod 600 ~/.ssh/my_key.pub
        cat ~/.ssh/my_key.pub
        
        ssh-keyscan -H 45.33.14.185 >> ~/.ssh/known_hosts
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/id_rsa
        
        rsync -avz --delete -e "ssh -i ~/.ssh/id_rsa" ./build/ root@45.33.14.185:/var/www/portfolio_prod/personal-portfolio-updated/build/
        rsync -avz --delete -e "ssh -i ~/.ssh/id_rsa" ./ root@45.33.14.185:/var/www/portfolio_prod/personal-portfolio-updated/
        ssh -i ~/.ssh/id_rsa root@45.33.14.185 'systemctl reload nginx'
